### ISSUE TITLE
[Arma3] server name / hostname "NOT SET"

### ISSUE THREAD

**Issue by TheLukio** [dgibbs64/linuxgsm#462]
I have no idea what happened, but since the 1.48 update to A3, when I do ./arma3server start it says "[  OK  ] Starting arma3-serverc: NOT SET". 

However everything looks "ok"...

ARMA 3 Server Details
========================================================================================================================================================
Server name:      NOT SET
Server IP:        x.x.x.x:2302
Server password:  xy
Admin password:   NOT SET
Slots:            20
Status:           ONLINE

only thing that seems off is:

arma3server Script Details
========================================================================================================================================================
column: .fn_details_gameserver: No such file or directory

Unfortunately In the server listing, the server pops up under it's domain hostname, not the name defined in the server.cfg, although a hostname is defined under hostname="defaulthostname";

Startup parameters and paths look correct, but it's as if the named defaulthostname.server.cfg and defaulthostname.network.cfg is being ignored

**Comment by dgibbs64** [comment]
Can I have the full output of ./arma3server details minus passwords and the config files. You can use something like pastebin etc and link them in this post.

**Comment by dgibbs64** [comment]
I have fixed a few bugs. Please can you test for me and let me know if there are still issues

**Comment by TheLukio** [comment]
Will give the new version a go, cheers!

Full details output:
[  OK  ] Starting vanillarepublic: NOT SET
gameserver@tektroopserver:~$ ./arma3server details

Distro Details
================================================================================
Distro:    Debian GNU/Linux 7.8 (wheezy)
Arch:      x86_64
Kernel:    3.2.0-4-amd64
Hostname:  ---
tmux:      tmux 1.6
GLIBC:     2.13

Performance
================================================================================
Uptime:    7d, 8h, 43m
Avg Load:  0.13, 0.64, 0.94

Mem:       total   used   free
Physical:  3.7G    1.8G   1.9G
Swap:      7.7G    0B     7.7G

Storage
================================================================================
Filesystem:   /dev/sda6
Total:        442G
Used:         9.6G
Available:    410G
Serverfiles:  9.4G
Backups:      3.1G

ARMA 3 Server Details
================================================================================
Server name:      NOT SET
Server IP:        192.168.178.59:2302
Server password:  ---
Admin password:   NOT SET
Slots:            20
Status:           ONLINE

arma3server Script Details
================================================================================
column: .fn_details_gameserver: No such file or directory

Backups
================================================================================
No. of backups:    1
Latest backup:
    date:          Thu Jun 11 14:16:09 CEST 2015
    file:          /home/arma3/backups/arma3-server-2015-06-11-140951.tar.gz
    size:          3.1G

Command-line Parameters
================================================================================
./arma3server -name=vanillarepublic -netlog -ip=192.168.178.59 -cfg=/home/arma3/serverfiles/cfg/---.network.cfg -config=/home/arma3/serverfiles/cfg/---.server.cfg -mod=curator\;kart\;heli\;mark\;dlcbundle\;@cba_a3\;@task_force_radio\;@bcombat

Ports
================================================================================
Change ports by editing the parameters in
/home/arma3/serverfiles/cfg/---.server.cfg.

Useful port diagnostic command:
netstat -atunp | grep arma3server

DESCRIPTION              DIRECTION  PORT  PROTOCOL
> Game                   INBOUND    2302  udp
> Steam: Query           INBOUND    2303  udp
> Steam: Master traffic  INBOUND    2304  udp

Status: ONLINE

**Comment by dgibbs64** [comment]
is there still an issue or is this now resolved?

**Comment by TheLukio** [comment]
Sorry for getting back to you for so long. In the meanwhile I've updated to the newest arma3server gsm, but to no avail. Since everything else seems to be working appropriately although I'm still getting the NOT SET text, I'm assuming something is borked, but the system is working.

**Comment by TheLukio** [comment]
Hello dgibb64.

I've finally found the issue and you may be pleased to hear that it is not related to the GSM, but to the way ARMA3 server has been ported to linux.

To elaborate. The game creates a default profile, named Player.profile in the directory
/.local/share/Arma 3 - Other Profiles/Player

Usually the server string to start up with a different named profile would entail using -profiles=<profilename>, but that does not work with Arma 3. The correct thing to do is use -name=<profilename>, which I had omitted. 

After adding this all looks well and the dreaded NOT SET demon has been sent back to where it came from!

Thank you for making this little tool, it has saved me many more grey hairs! :-)
